---
testFramework:
  enabled: false

service:
  enabled: true
  type: NodePort
  nodePort: 30001

persistence:
  enabled: true
  storageClassName: standard

adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.default
        access: proxy
        isDefault: true
      - name: Linkerd Node graph
        type: hamedkarbasi93-nodegraphapi-datasource
        access: proxy
        url: http://linkerd-grafana-graph.default

plugins:
  - hamedkarbasi93-nodegraphapi-datasource

grafana.ini:
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin
