---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.21.14@sha256:ad5b7446dd8332439f22a1efdac73670f0da158c00f0a70b45716e7ef3fae20b
    extraPortMappings:
      # Prometheus
      - containerPort: 30000
        hostPort: 9090
        listenAddress: "0.0.0.0"
        protocol: tcp

      # Grafana
      - containerPort: 30001
        hostPort: 3000
        listenAddress: "0.0.0.0"
        protocol: tcp

      # Linkerd's frontend
      - containerPort: 30002
        hostPort: 8080
        listenAddress: "0.0.0.0"
        protocol: tcp
