---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-grafana-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd-grafana-graph
  template:
    metadata:
      labels:
        app: linkerd-grafana-graph
    spec:
      containers:
        - name: nodegraph-server
          image: linkerd-grafana-graph:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-grafana-graph
spec:
  ports:
    - port: 80
      targetPort: 5001
  selector:
    app: linkerd-grafana-graph
